# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'formulario.ui'
#
# Created: Thu Oct 26 14:27:13 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(480, 319)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.le_descripcion = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.le_descripcion.setFont(font)
        self.le_descripcion.setObjectName("le_descripcion")
        self.verticalLayout.addWidget(self.le_descripcion)
        self.le_categoria = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.le_categoria.setFont(font)
        self.le_categoria.setObjectName("le_categoria")
        self.verticalLayout.addWidget(self.le_categoria)
        self.le_proveedor = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.le_proveedor.setFont(font)
        self.le_proveedor.setObjectName("le_proveedor")
        self.verticalLayout.addWidget(self.le_proveedor)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.le_precio_unitario = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.le_precio_unitario.setFont(font)
        self.le_precio_unitario.setObjectName("le_precio_unitario")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_precio_unitario)
        self.label_2 = QtGui.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.sb_cantidad_inventario = QtGui.QSpinBox(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.sb_cantidad_inventario.setFont(font)
        self.sb_cantidad_inventario.setObjectName("sb_cantidad_inventario")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.sb_cantidad_inventario)
        self.verticalLayout.addLayout(self.formLayout)
        self.le_codigo = QtGui.QLineEdit(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.le_codigo.setFont(font)
        self.le_codigo.setObjectName("le_codigo")
        self.verticalLayout.addWidget(self.le_codigo)
        self.btn_aceptar = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.btn_aceptar.setFont(font)
        self.btn_aceptar.setObjectName("btn_aceptar")
        self.verticalLayout.addWidget(self.btn_aceptar)
        self.btn_cancelar = QtGui.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        self.btn_cancelar.setFont(font)
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.verticalLayout.addWidget(self.btn_cancelar)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_descripcion, self.le_categoria)
        Form.setTabOrder(self.le_categoria, self.le_proveedor)
        Form.setTabOrder(self.le_proveedor, self.le_precio_unitario)
        Form.setTabOrder(self.le_precio_unitario, self.sb_cantidad_inventario)
        Form.setTabOrder(self.sb_cantidad_inventario, self.le_codigo)
        Form.setTabOrder(self.le_codigo, self.btn_aceptar)
        Form.setTabOrder(self.btn_aceptar, self.btn_cancelar)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Formulario", None, QtGui.QApplication.UnicodeUTF8))
        self.le_descripcion.setPlaceholderText(QtGui.QApplication.translate("Form", "Descripción", None, QtGui.QApplication.UnicodeUTF8))
        self.le_categoria.setPlaceholderText(QtGui.QApplication.translate("Form", "Categoría", None, QtGui.QApplication.UnicodeUTF8))
        self.le_proveedor.setPlaceholderText(QtGui.QApplication.translate("Form", "Proveedor", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Precio Unitario", None, QtGui.QApplication.UnicodeUTF8))
        self.le_precio_unitario.setText(QtGui.QApplication.translate("Form", "$", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Cantidad en Inventario", None, QtGui.QApplication.UnicodeUTF8))
        self.le_codigo.setPlaceholderText(QtGui.QApplication.translate("Form", "Código", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_aceptar.setText(QtGui.QApplication.translate("Form", "ACEPTAR", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_cancelar.setText(QtGui.QApplication.translate("Form", "CANCELAR", None, QtGui.QApplication.UnicodeUTF8))

