-- MySQL Script generated by MySQL Workbench
-- Thu Sep 21 17:58:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabajador` (
  `rut` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido_p` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`rut`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `rut` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rut`),
  CONSTRAINT `rut`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`Trabajador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingreso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingreso` (
  `idIngreso` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(10) NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`idIngreso`),
  INDEX `rut_idx` (`rut` ASC),
  CONSTRAINT `rut`
    FOREIGN KEY (`rut`)
    REFERENCES `mydb`.`Trabajador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Informe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Informe` (
  `idInforme` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `ingresoTotal` INT NOT NULL,
  `ganancia` INT NOT NULL,
  `rutTrabajador` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idInforme`),
  INDEX `rutTrabajador_idx` (`rutTrabajador` ASC),
  CONSTRAINT `rutTrabajador`
    FOREIGN KEY (`rutTrabajador`)
    REFERENCES `mydb`.`Trabajador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL,
  `fecha` DATETIME NULL,
  `rutTrabajador` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `rutTrabajador_idx` (`rutTrabajador` ASC),
  CONSTRAINT `rutTrabajador`
    FOREIGN KEY (`rutTrabajador`)
    REFERENCES `mydb`.`Trabajador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `codigo` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `precio` INT NOT NULL,
  `proveedor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventario` (
  `idInventario` INT NOT NULL,
  `codigoProducto` INT NOT NULL,
  `stock` INT NULL,
  PRIMARY KEY (`idInventario`),
  INDEX `codigoProducto_idx` (`codigoProducto` ASC),
  CONSTRAINT `codigoProducto`
    FOREIGN KEY (`codigoProducto`)
    REFERENCES `mydb`.`Producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venta_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venta_producto` (
  `idVenta` INT NOT NULL,
  `codigoProducto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idVenta`, `codigoProducto`),
  INDEX `codigoProducto_idx` (`codigoProducto` ASC),
  CONSTRAINT `idVenta`
    FOREIGN KEY (`idVenta`)
    REFERENCES `mydb`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoProducto`
    FOREIGN KEY (`codigoProducto`)
    REFERENCES `mydb`.`Producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modifica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modifica` (
  `idModifica` INT NOT NULL,
  `rutTrabajador` VARCHAR(10) NOT NULL,
  `idInventario` INT NOT NULL,
  `codigoProducto` INT NOT NULL,
  `accion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idModifica`),
  INDEX `rutTrabajador_idx` (`rutTrabajador` ASC),
  INDEX `idInventario_idx` (`idInventario` ASC),
  INDEX `codigoProducto_idx` (`codigoProducto` ASC),
  CONSTRAINT `rutTrabajador`
    FOREIGN KEY (`rutTrabajador`)
    REFERENCES `mydb`.`Trabajador` (`rut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idInventario`
    FOREIGN KEY (`idInventario`)
    REFERENCES `mydb`.`Inventario` (`idInventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `codigoProducto`
    FOREIGN KEY (`codigoProducto`)
    REFERENCES `mydb`.`Producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
